// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdkO0P8NrQvwFtoc0gciZ53at5XLbQNjo',
    appId: '1:677323176926:web:bc469c9681f692591f3b4f',
    messagingSenderId: '677323176926',
    projectId: 'flutter-tasks-774ce',
    authDomain: 'flutter-tasks-774ce.firebaseapp.com',
    storageBucket: 'flutter-tasks-774ce.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC94uIVeu46c3T-vbn3sayFjEbv9OwY5Qs',
    appId: '1:677323176926:android:91f65c6a75fbb3801f3b4f',
    messagingSenderId: '677323176926',
    projectId: 'flutter-tasks-774ce',
    storageBucket: 'flutter-tasks-774ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDO9tQ2Kesthv2RZbVDYPcIO8OpybWoDnU',
    appId: '1:677323176926:ios:ba7b0b2d8e0f8e841f3b4f',
    messagingSenderId: '677323176926',
    projectId: 'flutter-tasks-774ce',
    storageBucket: 'flutter-tasks-774ce.appspot.com',
    androidClientId:
        '677323176926-irjq1k6l6p271egkta66c12uel8rnf1t.apps.googleusercontent.com',
    iosClientId:
        '677323176926-i4j80ogcqcokdd5b1dbpm094b7bkj7ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTasks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDO9tQ2Kesthv2RZbVDYPcIO8OpybWoDnU',
    appId: '1:677323176926:ios:ba7b0b2d8e0f8e841f3b4f',
    messagingSenderId: '677323176926',
    projectId: 'flutter-tasks-774ce',
    storageBucket: 'flutter-tasks-774ce.appspot.com',
    androidClientId:
        '677323176926-irjq1k6l6p271egkta66c12uel8rnf1t.apps.googleusercontent.com',
    iosClientId:
        '677323176926-i4j80ogcqcokdd5b1dbpm094b7bkj7ef.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTasks',
  );
}
